language: java
jdk: oraclejdk8
before_install:
- '[ "$TRAVIS_PULL_REQUEST" == "false" ] && openssl aes-256-cbc -K $encrypted_4ae939a0e316_key -iv $encrypted_4ae939a0e316_iv -in secring.gpg.enc -out secring.gpg -d || echo "no decryption for pull requests"'
